"""Bundled global-bird catalog: regional filtering, fuzzy search, alpha-code lookup.

Loads ``analyzer/models/birds/birds_global.csv`` (generated by
``tools/build_bird_catalog.py``) and exposes a small query API used by the
API bridge to populate the species combobox.

The catalog never touches the ML model's labels or its predictions -- it only
gates which species the user can *manually apply* and how those species render
in the UI. Every model-label row is included regardless of region selection
is irrelevant: region filtering is applied *outside* this layer, in the
combobox query path.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from .config import MODELS_DIR

CATALOG_PATH = MODELS_DIR / "birds" / "birds_global.csv"
ZH_NAMES_PATH = MODELS_DIR / "birds" / "zh_hant_names.csv"

# Region codes that ``Settings`` may legally store. Kept here -- not in
# ``settings_utils`` -- so the data layer owns the vocabulary and the
# settings sanitiser just imports it.
ALLOWED_REGION_CODES: tuple[str, ...] = (
    "NA", "MA", "SA", "AF", "PAL", "OR", "AU", "AN",
    "AO", "PO", "IO", "SO", "TrO", "Worldwide",
)

REGION_LABELS: dict[str, str] = {
    "NA":        "North America",
    "MA":        "Middle America & Caribbean",
    "SA":        "South America",
    "AF":        "Africa",
    "PAL":       "Eurasia (Palearctic)",
    "OR":        "South & SE Asia (Oriental)",
    "AU":        "Australasia",
    "AN":        "Antarctic",
    "AO":        "Atlantic Ocean",
    "PO":        "Pacific Ocean",
    "IO":        "Indian Ocean",
    "SO":        "Southern Ocean",
    "TrO":       "Tropical Oceans",
    "Worldwide": "Worldwide (cosmopolitan species)",
}

DEFAULT_REGION_SELECTION: tuple[str, ...] = ("OR", "PAL",)


@dataclass(frozen=True)
class BirdRecord:
    canonical_common_name: str
    scientific_name: str
    family_sci: str
    family_common: str
    order: str
    regions: frozenset[str]
    alpha_4: str
    aliases: tuple[str, ...]
    is_model_species: bool
    name_zh: str = ""

    def matches_any_region(self, selected: frozenset[str]) -> bool:
        """True if at least one of ``regions`` is in ``selected``.

        A 'Worldwide' species always matches when *any* region is selected,
        because by definition it occurs across all the standard biogeographic
        regions and a user filtering down to (say) NA would still expect it
        in their list.
        """
        if not selected:
            return False
        if "Worldwide" in self.regions:
            return True
        return not selected.isdisjoint(self.regions)


@dataclass(frozen=True)
class FamilyEntry:
    family_common: str
    family_sci: str
    order: str
    regions: frozenset[str]

    def matches_any_region(self, selected: frozenset[str]) -> bool:
        if not selected:
            return False
        if "Worldwide" in self.regions:
            return True
        return not selected.isdisjoint(self.regions)


def _parse_regions(s: str) -> frozenset[str]:
    if not s:
        return frozenset()
    return frozenset(p for p in (t.strip() for t in s.split(",")) if p)


def _parse_aliases(s: str) -> tuple[str, ...]:
    if not s:
        return ()
    return tuple(p for p in (t.strip() for t in s.split("|")) if p)


def load_zh_names(path: Path | None = None) -> dict[str, str]:
    """Map scientific name -> Traditional Chinese display name.

    Missing file yields an empty map so the English catalog still loads.
    """
    p = Path(path) if path is not None else ZH_NAMES_PATH
    out: dict[str, str] = {}
    if not p.is_file():
        return out
    with open(p, encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            sci = (row.get("scientific_name") or "").strip()
            name = (row.get("name_zh") or "").strip()
            if sci and name:
                out[sci] = name
    return out


def load_catalog(path: Path | None = None) -> list[BirdRecord]:
    """Read the bundled CSV. Skips header-equivalent or empty rows defensively."""
    p = Path(path) if path is not None else CATALOG_PATH
    zh_names = load_zh_names(p.parent / "zh_hant_names.csv")
    out: list[BirdRecord] = []
    with open(p, encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            name = (row.get("canonical_common_name") or "").strip()
            if not name:
                continue
            sci = (row.get("scientific_name") or "").strip()
            out.append(BirdRecord(
                canonical_common_name=name,
                scientific_name=sci,
                family_sci=(row.get("family_sci") or "").strip(),
                family_common=(row.get("family_common") or "").strip(),
                order=(row.get("order") or "").strip(),
                regions=_parse_regions(row.get("regions") or ""),
                alpha_4=(row.get("alpha_4") or "").strip().upper(),
                aliases=_parse_aliases(row.get("aliases") or ""),
                is_model_species=(row.get("is_model_species") or "").strip() == "1",
                name_zh=zh_names.get(sci, ""),
            ))
    return out


# ----------------------------------------------------------------------------
# Fuzzy search
# ----------------------------------------------------------------------------
#
# We rank candidates with a small scoring function that prioritises (in order):
#   1. Exact 4-letter code match (e.g. "amro" -> American Robin)
#   2. Exact common-name or alias match
#   3. Common-name prefix match
#   4. Token-prefix match (each typed token prefixes some word in the name)
#   5. Subsequence match (letters appear in order: "amrob" -> "American Robin")
#   6. Substring match (the typed string appears anywhere)
#
# Each tier is non-overlapping (higher tier wins). Within a tier we break ties
# by alphabetical canonical name so the ordering is stable and predictable.
#
# Scientific-name and alias hits use the same tiers but with a small penalty
# so that an exact common-name hit always outranks an alias exact hit. This
# keeps results predictable when the same string appears in multiple fields.

_SCORE_ALPHA_EXACT     = 1000
_SCORE_COMMON_EXACT    = 900
_SCORE_ALIAS_EXACT     = 880
_SCORE_SCI_EXACT       = 860
_SCORE_COMMON_PREFIX   = 800
_SCORE_ALIAS_PREFIX    = 770
_SCORE_SCI_PREFIX      = 750
_SCORE_TOKEN_PREFIX    = 700
_SCORE_SUBSEQUENCE     = 600
_SCORE_SUBSTRING       = 500
_SCORE_SCI_SUBSTRING   = 450


def _tokens(s: str) -> list[str]:
    # Split on whitespace and hyphens; lowercase. Keep apostrophes (e.g. "Wilson's").
    out: list[str] = []
    cur: list[str] = []
    for ch in s.lower():
        if ch.isalnum() or ch == "'":
            cur.append(ch)
        else:
            if cur:
                out.append("".join(cur))
                cur = []
    if cur:
        out.append("".join(cur))
    return out


def _is_subsequence(needle: str, haystack: str) -> bool:
    """True if ``needle``'s letters appear in order within ``haystack``.

    Both must already be lowercased. Skips non-alphanumerics in ``haystack`` so
    "amrob" matches "americanrobin" -> derived from "American Robin".
    """
    if not needle:
        return True
    i = 0
    for ch in haystack:
        if not (ch.isalnum() or ch == "'"):
            continue
        if ch == needle[i]:
            i += 1
            if i == len(needle):
                return True
    return False


def _token_prefix_match(query_tokens: list[str], target_tokens: list[str]) -> bool:
    """Every query token must be a prefix of some unique target token."""
    if not query_tokens:
        return True
    if len(query_tokens) > len(target_tokens):
        return False
    used = [False] * len(target_tokens)
    for q in query_tokens:
        matched = False
        for i, t in enumerate(target_tokens):
            if not used[i] and t.startswith(q):
                used[i] = True
                matched = True
                break
        if not matched:
            return False
    return True


def score_record(query: str, rec: BirdRecord) -> int:
    """Return a non-negative match score. ``0`` means no match.

    The scoring is intentionally simple and deterministic; see the module
    docstring for the tier ordering. Higher is better.
    """
    q = (query or "").strip().lower()
    if not q:
        return 0

    common = rec.canonical_common_name.lower()
    sci = rec.scientific_name.lower()
    aliases_lower = [a.lower() for a in rec.aliases]
    alpha = rec.alpha_4.lower()
    zh = (rec.name_zh or "").strip()

    # 1. Alpha-4 exact match (case-insensitive)
    if alpha and len(q) == 4 and q == alpha:
        return _SCORE_ALPHA_EXACT

    # 2. Exact field matches
    if q == common:
        return _SCORE_COMMON_EXACT
    if zh and q == zh:
        return _SCORE_COMMON_EXACT
    if q in aliases_lower:
        return _SCORE_ALIAS_EXACT
    if q == sci:
        return _SCORE_SCI_EXACT

    # 3. Prefix matches
    if common.startswith(q):
        return _SCORE_COMMON_PREFIX
    if zh and zh.startswith(q):
        return _SCORE_COMMON_PREFIX
    if any(a.startswith(q) for a in aliases_lower):
        return _SCORE_ALIAS_PREFIX
    if sci.startswith(q):
        return _SCORE_SCI_PREFIX

    # 4. Token-prefix on common name. Each query token must prefix a word.
    qt = _tokens(q)
    if qt and _token_prefix_match(qt, _tokens(common)):
        return _SCORE_TOKEN_PREFIX

    # 5. Subsequence on alpha-stripped common name. Handles "amrob" -> American Robin
    common_compact = "".join(c for c in common if c.isalnum() or c == "'")
    q_compact = "".join(c for c in q if c.isalnum() or c == "'")
    if q_compact and _is_subsequence(q_compact, common_compact):
        return _SCORE_SUBSEQUENCE

    # 6. Substring matches
    if q in common or any(q in a for a in aliases_lower):
        return _SCORE_SUBSTRING
    if zh and q in zh:
        return _SCORE_SUBSTRING
    if q in sci:
        return _SCORE_SCI_SUBSTRING

    return 0


def score_family(query: str, entry: FamilyEntry) -> int:
    """Score a family entry against a search query. Same tier logic as
    ``score_record`` but limited to family_common and family_sci fields."""
    q = (query or "").strip().lower()
    if not q:
        return 0

    common = entry.family_common.lower()
    sci = entry.family_sci.lower()

    if q == common:
        return _SCORE_COMMON_EXACT
    if q == sci:
        return _SCORE_SCI_EXACT

    if common.startswith(q):
        return _SCORE_COMMON_PREFIX
    if sci.startswith(q):
        return _SCORE_SCI_PREFIX

    qt = _tokens(q)
    if qt and _token_prefix_match(qt, _tokens(common)):
        return _SCORE_TOKEN_PREFIX

    common_compact = "".join(c for c in common if c.isalnum() or c == "'")
    q_compact = "".join(c for c in q if c.isalnum() or c == "'")
    if q_compact and _is_subsequence(q_compact, common_compact):
        return _SCORE_SUBSEQUENCE

    if q in common:
        return _SCORE_SUBSTRING
    if q in sci:
        return _SCORE_SCI_SUBSTRING

    return 0


class BirdCatalog:
    """In-memory catalog wrapper with region filtering and ranked search."""

    def __init__(self, records: list[BirdRecord] | None = None):
        self._records: list[BirdRecord] = records if records is not None else load_catalog()
        # Indices for O(1) exact-name lookup. Lowercased keys.
        self._by_common: dict[str, BirdRecord] = {}
        self._by_alpha: dict[str, BirdRecord] = {}
        # Map of family display name -> scientific family. Populated from
        # every record that has both fields so the JS layer can render
        # family_sci subtext on a family-tier pill without needing a
        # sibling species record to be present in the same scene.
        self._family_common_to_sci: dict[str, str] = {}
        # Aggregated family entries for the family combobox search.
        _fam_regions: dict[str, set[str]] = {}
        _fam_order: dict[str, str] = {}
        for r in self._records:
            self._by_common[r.canonical_common_name.lower()] = r
            if r.alpha_4:
                self._by_alpha.setdefault(r.alpha_4.lower(), r)
            if r.family_common and r.family_sci:
                self._family_common_to_sci.setdefault(r.family_common, r.family_sci)
            if r.family_common:
                _fam_regions.setdefault(r.family_common, set()).update(r.regions)
                if r.order:
                    _fam_order.setdefault(r.family_common, r.order)
        self._families: list[FamilyEntry] = []
        for fc, sci in self._family_common_to_sci.items():
            self._families.append(FamilyEntry(
                family_common=fc,
                family_sci=sci,
                order=_fam_order.get(fc, ""),
                regions=frozenset(_fam_regions.get(fc, ())),
            ))

    @property
    def records(self) -> list[BirdRecord]:
        return self._records

    def __len__(self) -> int:
        return len(self._records)

    def lookup(self, canonical_name: str) -> BirdRecord | None:
        if not canonical_name:
            return None
        return self._by_common.get(canonical_name.strip().lower())

    def lookup_by_alpha(self, code: str) -> BirdRecord | None:
        if not code or len(code) != 4:
            return None
        return self._by_alpha.get(code.strip().lower())

    def family_sci_for(self, family_common: str) -> str:
        """Return the scientific family name for a family display name, or
        '' if no record carries that family. Used by the bridge to expose
        a direct family_common -> family_sci lookup to the JS layer."""
        if not family_common:
            return ""
        return self._family_common_to_sci.get(family_common.strip(), "")

    @property
    def family_sci_map(self) -> dict[str, str]:
        """Full family_common -> family_sci mapping (copy, not the
        underlying dict). The JS hydrates this once at startup so family
        pills can resolve sci subtext directly."""
        return dict(self._family_common_to_sci)

    def filter(self, regions: Iterable[str]) -> list[BirdRecord]:
        """Return records that have at least one region in ``regions``.

        Empty ``regions`` -> empty list. ``Worldwide`` species match against
        any non-empty selection.
        """
        sel = frozenset(r for r in regions if r)
        if not sel:
            return []
        return [r for r in self._records if r.matches_any_region(sel)]

    def search(self, query: str, regions: Iterable[str], limit: int = 20) -> list[BirdRecord]:
        """Region-filtered fuzzy search. Returns up to ``limit`` ranked records.

        With an empty query, returns the alphabetical head of the region's
        catalog -- this matches the existing combobox UX (the dropdown is
        always populated, even before the user types).
        """
        sel = frozenset(r for r in regions if r)
        if not sel:
            return []
        q = (query or "").strip()
        if not q:
            in_region = [r for r in self._records if r.matches_any_region(sel)]
            in_region.sort(key=lambda r: r.canonical_common_name.lower())
            return in_region[:limit]

        scored: list[tuple[int, str, BirdRecord]] = []
        for rec in self._records:
            if not rec.matches_any_region(sel):
                continue
            s = score_record(q, rec)
            if s > 0:
                scored.append((s, rec.canonical_common_name.lower(), rec))
        # Sort: descending score, then alphabetical (lowercased name)
        scored.sort(key=lambda t: (-t[0], t[1]))
        return [rec for _, _, rec in scored[:limit]]

    def search_families(self, query: str, regions: Iterable[str], limit: int = 20) -> list[FamilyEntry]:
        """Region-filtered fuzzy search across unique families."""
        sel = frozenset(r for r in regions if r)
        if not sel:
            return []
        q = (query or "").strip()
        if not q:
            in_region = [f for f in self._families if f.matches_any_region(sel)]
            in_region.sort(key=lambda f: f.family_common.lower())
            return in_region[:limit]

        scored: list[tuple[int, str, FamilyEntry]] = []
        for entry in self._families:
            if not entry.matches_any_region(sel):
                continue
            s = score_family(q, entry)
            if s > 0:
                scored.append((s, entry.family_common.lower(), entry))
        scored.sort(key=lambda t: (-t[0], t[1]))
        return [entry for _, _, entry in scored[:limit]]


_catalog_singleton: BirdCatalog | None = None


def get_catalog() -> BirdCatalog:
    """Process-wide singleton (loaded once on first access)."""
    global _catalog_singleton
    if _catalog_singleton is None:
        _catalog_singleton = BirdCatalog()
    return _catalog_singleton


def record_to_dict(rec: BirdRecord) -> dict:
    """JSON-serializable representation used by the API bridge."""
    return {
        "canonical_common_name": rec.canonical_common_name,
        "scientific_name": rec.scientific_name,
        "family_sci": rec.family_sci,
        "family_common": rec.family_common,
        "order": rec.order,
        "regions": sorted(rec.regions),
        "alpha_4": rec.alpha_4,
        "aliases": list(rec.aliases),
        "is_model_species": rec.is_model_species,
        "name_zh": rec.name_zh,
    }


def family_entry_to_dict(entry: FamilyEntry) -> dict:
    """JSON-serializable representation of a family entry."""
    return {
        "family_common": entry.family_common,
        "family_sci": entry.family_sci,
        "order": entry.order,
        "regions": sorted(entry.regions),
    }
